/*
 * Contenido creado por los integrantes
 * del Grupo #2, prohibida su reutilizaci�n.
 * 
 *  - Alessandra Varisco
 *  - Carlos Hurtado
 *  - Carlos Verde
 */
package Interfaces;

import Clases.Agregado;
import Clases.GrupoAfiliacionC;
import Clases.ProfesionC;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author cverd
 */
public class GrupoAfiliacionList extends javax.swing.JFrame {

    private int baseO;
    private boolean isMudanza = false;
    
    /**
     * Creates new form ParafernaliaList
     */
    public GrupoAfiliacionList() {
        
        initComponents();
       
        
        fillTable();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setTitle("Grupo de Afiliacion");
        
        tableGrupoAfiliacion.addMouseListener(new MouseAdapter() 
        {
           public void mouseClicked(MouseEvent e) 
           {
               
            DefaultTableModel model = (DefaultTableModel) tableGrupoAfiliacion.getModel();    
        
              int fila = tableGrupoAfiliacion.rowAtPoint(e.getPoint());
              int columna = tableGrupoAfiliacion.columnAtPoint(e.getPoint());
              if ((fila > -1) && (columna > -1)){
                  
                  int id = (int) model.getValueAt(fila, 0);
                  
                  System.out.println(id);
                  txtIDGrupoAfiliacion.setText(Integer.toString(id));
                
              }
           }
        });
    }

    
    public void emptyTable(){
        DefaultTableModel model = (DefaultTableModel) tableGrupoAfiliacion.getModel();
        
        int filas = tableGrupoAfiliacion.getRowCount();
        for (int i = 1; i <= filas; i++){
            model.removeRow(0);
        }
    }
   
    public void fillTable(){
        emptyTable();
        
        JSONArray listaGrupoAfiliacion = GrupoAfiliacionC.getGruposAfiliacion();
        DefaultTableModel model = (DefaultTableModel) tableGrupoAfiliacion.getModel();        
        
        for (int i = 0; i<listaGrupoAfiliacion.length(); i++){
            JSONObject grupoAfiliacion = listaGrupoAfiliacion.getJSONObject(i);
            
            model.addRow(new Object[]{grupoAfiliacion.getInt("id"),grupoAfiliacion.getString("name"), grupoAfiliacion.getString("desc"), grupoAfiliacion.getDouble("ipa"), grupoAfiliacion.getString("base"), grupoAfiliacion.getString("dir")});
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrupoAfiliacion = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAddGrupoAfiliacion = new javax.swing.JButton();
        txtNameGrupoAfiliacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescGrupoAfiliacion = new javax.swing.JTextArea();
        txtCiudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtBaseOperaciones = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescBaseOperaciones = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtIDGrupoAfiliacion = new javax.swing.JTextField();
        btnDelGrupoAfiliacion = new javax.swing.JButton();
        btnModGrupoAfiliacion = new javax.swing.JButton();
        panelModProfesion = new javax.swing.JPanel();
        btnUpdateGrupoAfiliacion = new javax.swing.JButton();
        txtNameGrupoAfiliacion_m = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescGrupoAfiliacion_m = new javax.swing.JTextArea();
        txtIDGrupoAfiliacion_m = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIPA_m = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEstado_m = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPais_m = new javax.swing.JTextField();
        txtCiudad_m = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBaseOperaciones_m = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescBaseOperaciones_m = new javax.swing.JTextArea();
        isMoving = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        txtIDBase_m = new javax.swing.JTextField();
        btnAtrasPL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(34, 38, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        tableGrupoAfiliacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripccion", "Ind. Poder Aumentado", "Base", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableGrupoAfiliacion);
        if (tableGrupoAfiliacion.getColumnModel().getColumnCount() > 0) {
            tableGrupoAfiliacion.getColumnModel().getColumn(0).setMinWidth(40);
            tableGrupoAfiliacion.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableGrupoAfiliacion.getColumnModel().getColumn(0).setMaxWidth(40);
            tableGrupoAfiliacion.getColumnModel().getColumn(1).setPreferredWidth(10);
            tableGrupoAfiliacion.getColumnModel().getColumn(2).setPreferredWidth(10);
            tableGrupoAfiliacion.getColumnModel().getColumn(3).setPreferredWidth(2);
        }

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar"));

        btnAddGrupoAfiliacion.setBackground(new java.awt.Color(0, 153, 51));
        btnAddGrupoAfiliacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddGrupoAfiliacion.setForeground(new java.awt.Color(255, 255, 255));
        btnAddGrupoAfiliacion.setText("AGREGAR");
        btnAddGrupoAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrupoAfiliacionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE GRUPO AFILIACION:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DESCRIPCION GRUPO AFILIACION:");

        txtDescGrupoAfiliacion.setColumns(20);
        txtDescGrupoAfiliacion.setRows(5);
        jScrollPane2.setViewportView(txtDescGrupoAfiliacion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CIUDAD:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PAIS:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ESTADO:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("BASE DE OPERACIONES:");

        txtDescBaseOperaciones.setColumns(20);
        txtDescBaseOperaciones.setRows(5);
        jScrollPane4.setViewportView(txtDescBaseOperaciones);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DESCRIPCION BASE DE OPERACIONES:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameGrupoAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtBaseOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddGrupoAfiliacion)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane4)
                                .addGap(33, 33, 33)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, 0)
                                .addComponent(txtBaseOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, 0)
                                .addComponent(txtNameGrupoAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnAddGrupoAfiliacion))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDGrupoAfiliacion.setEditable(false);

        btnDelGrupoAfiliacion.setText("ELIMINAR");
        btnDelGrupoAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelGrupoAfiliacionActionPerformed(evt);
            }
        });

        btnModGrupoAfiliacion.setText("MODIFICAR");
        btnModGrupoAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModGrupoAfiliacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIDGrupoAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnModGrupoAfiliacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelGrupoAfiliacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIDGrupoAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModGrupoAfiliacion)
                    .addComponent(btnDelGrupoAfiliacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelModProfesion.setBackground(new java.awt.Color(153, 153, 153));
        panelModProfesion.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar"));

        btnUpdateGrupoAfiliacion.setBackground(new java.awt.Color(0, 153, 51));
        btnUpdateGrupoAfiliacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdateGrupoAfiliacion.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateGrupoAfiliacion.setText("ACTUALIZAR");
        btnUpdateGrupoAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGrupoAfiliacionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOMBRE:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DESCRIPCION:");

        txtDescGrupoAfiliacion_m.setColumns(20);
        txtDescGrupoAfiliacion_m.setRows(5);
        jScrollPane3.setViewportView(txtDescGrupoAfiliacion_m);

        txtIDGrupoAfiliacion_m.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID GRUPO:");

        txtIPA_m.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ind. Poder Aumentado:");

        txtEstado_m.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ESTADO:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PAIS:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CIUDAD:");

        txtPais_m.setEditable(false);

        txtCiudad_m.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BASE DE OPERACIONES:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DESCRIPCION BASE DE OPERACIONES:");

        txtDescBaseOperaciones_m.setColumns(20);
        txtDescBaseOperaciones_m.setRows(5);
        jScrollPane5.setViewportView(txtDescBaseOperaciones_m);

        isMoving.setText("Mudar");
        isMoving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isMovingActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID BASE:");

        txtIDBase_m.setEditable(false);

        javax.swing.GroupLayout panelModProfesionLayout = new javax.swing.GroupLayout(panelModProfesion);
        panelModProfesion.setLayout(panelModProfesionLayout);
        panelModProfesionLayout.setHorizontalGroup(
            panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModProfesionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModProfesionLayout.createSequentialGroup()
                        .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(txtNameGrupoAfiliacion_m, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModProfesionLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel18))
                            .addGroup(panelModProfesionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txtBaseOperaciones_m, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelModProfesionLayout.createSequentialGroup()
                        .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateGrupoAfiliacion)
                            .addComponent(txtIPA_m, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModProfesionLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIDBase_m, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModProfesionLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtIDGrupoAfiliacion_m, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(79, 79, 79)
                        .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModProfesionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addGroup(panelModProfesionLayout.createSequentialGroup()
                                    .addComponent(txtCiudad_m, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(txtEstado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelModProfesionLayout.createSequentialGroup()
                                    .addComponent(txtPais_m, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(isMoving))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelModProfesionLayout.setVerticalGroup(
            panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModProfesionLayout.createSequentialGroup()
                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18))
                .addGap(5, 5, 5)
                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameGrupoAfiliacion_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaseOperaciones_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModProfesionLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIPA_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtIDGrupoAfiliacion_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtIDBase_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnUpdateGrupoAfiliacion))
                    .addGroup(panelModProfesionLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModProfesionLayout.createSequentialGroup()
                                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPais_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(isMoving)))
                            .addGroup(panelModProfesionLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(panelModProfesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCiudad_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelModProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelModProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnAtrasPL.setBackground(new java.awt.Color(153, 0, 0));
        btnAtrasPL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtrasPL.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasPL.setText("ATRAS");
        btnAtrasPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAtrasPL)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAtrasPL)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasPLActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_btnAtrasPLActionPerformed

    private void btnAddGrupoAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrupoAfiliacionActionPerformed
        // TODO add your handling code here:
        
        
        if (!txtNameGrupoAfiliacion.getText().isEmpty()){
            if (!txtBaseOperaciones.getText().isEmpty()){
                if (!txtCiudad.getText().isEmpty()){
                    if (!txtEstado.getText().isEmpty()){
                        if (!txtPais.getText().isEmpty()){
                            
                            JSONObject grupo = new JSONObject();
                            JSONObject base = new JSONObject();
                            JSONObject dir = new JSONObject();
                            
                            grupo.put("name", txtNameGrupoAfiliacion.getText());
                            grupo.put("desc", (txtDescGrupoAfiliacion.getText().isEmpty()) ? "" : txtDescGrupoAfiliacion.getText());
                            
                            base.put("name", txtBaseOperaciones.getText());
                            base.put("desc", (txtDescBaseOperaciones.getText().isEmpty()) ? "" : txtDescBaseOperaciones.getText());
                            
                            dir.put("ciudad", txtCiudad.getText());
                            dir.put("estado", txtEstado.getText());
                            dir.put("pais", txtPais.getText());
                            
                            int idBase = GrupoAfiliacionC.createBaseOperaciones(base, dir);
                            int idGrupo = GrupoAfiliacionC.createGrupoAfiliacion(grupo);
                            
                            if (idGrupo > 0){
                                if (idBase > 0){
                                    if (GrupoAfiliacionC.createGaBo(idGrupo, idBase) == 0){
                                        
                                        txtNameGrupoAfiliacion.setText("");
                                        txtDescGrupoAfiliacion.setText("");
                                        txtBaseOperaciones.setText("");
                                        txtDescBaseOperaciones.setText("");
                                        txtCiudad.setText("");
                                        txtEstado.setText("");
                                        txtPais.setText("");
                                        
                                        fillTable();

                                    }
                                    else{
                                        GrupoAfiliacionC.deleteGrupoBase(idGrupo, idBase, false);
                                        JOptionPane.showMessageDialog(this, "Error al unir la Base y el Grupo, por integridad se han borrado ambos", "Error", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                                else{
                                    JOptionPane.showMessageDialog(this, "Error al crear la base", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(this, "Error al crear el grupo", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                            
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Pais no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Estado no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Ciudad no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Nombre de la base no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Nombre del grupo no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddGrupoAfiliacionActionPerformed

    private void btnDelGrupoAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelGrupoAfiliacionActionPerformed
        // TODO add your handling code here:
        
        if (!txtIDGrupoAfiliacion.getText().isEmpty()){
            if(GrupoAfiliacionC.deleteGBAll(Integer.parseInt(txtIDGrupoAfiliacion.getText())) == 0){
                fillTable();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al tratar de eliminar el Grupo y su Base", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un grupo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDelGrupoAfiliacionActionPerformed

    private void btnModGrupoAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModGrupoAfiliacionActionPerformed
        // TODO add your handling code here:
        
        JSONObject info = GrupoAfiliacionC.getGrupoAfiliacion(Integer.parseInt(txtIDGrupoAfiliacion.getText()));
        
        txtNameGrupoAfiliacion_m.setText(info.getString("name_grupo"));
        txtDescGrupoAfiliacion_m.setText(info.getString("desc_grupo"));
        txtBaseOperaciones_m.setText(info.getString("base_base"));
        txtDescBaseOperaciones_m.setText(info.getString("desc_base"));
        
        txtIPA_m.setText(Double.toString(info.getDouble("ipa_grupo")));
        
        txtIDGrupoAfiliacion_m.setText(Integer.toString(info.getInt("id_grupo")));
        txtIDBase_m.setText(Integer.toString(info.getInt("id_base")));
        
    }//GEN-LAST:event_btnModGrupoAfiliacionActionPerformed

    private void isMovingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isMovingActionPerformed
        // TODO add your handling code here:
        
        if (isMudanza){
            isMudanza = false;
            
            txtCiudad_m.setText("");
            txtEstado_m.setText("");
            txtPais_m.setText("");
            
            txtCiudad_m.setEditable(false);
            txtEstado_m.setEditable(false);
            txtPais_m.setEditable(false);
            
        }else{
            isMudanza = true;
            
            txtCiudad_m.setEditable(true);
            txtEstado_m.setEditable(true);
            txtPais_m.setEditable(true);
            
        }
        
    }//GEN-LAST:event_isMovingActionPerformed

    private void btnUpdateGrupoAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGrupoAfiliacionActionPerformed
        // TODO add your handling code here:
        
        JSONObject info = new JSONObject();
        
        if (!txtNameGrupoAfiliacion_m.getText().isEmpty()){
            if (!txtBaseOperaciones_m.getText().isEmpty()){
                
                if (isMoving.isSelected()){
                    
                    if (!txtCiudad_m.getText().isEmpty()){
                        if (!txtEstado_m.getText().isEmpty()){
                            if (!txtPais_m.getText().isEmpty()){

                                
                                info.put("isMoving", true);
                                
                                info.put("ciudad",txtCiudad_m.getText());
                                info.put("estado",txtEstado_m.getText());
                                info.put("pais",txtPais_m.getText()); 

                                info.put("name_grupo", txtNameGrupoAfiliacion_m.getText());
                                info.put("desc_grupo", txtDescGrupoAfiliacion_m.getText());
                                info.put("name_base", txtBaseOperaciones_m.getText());
                                info.put("desc_base", txtDescBaseOperaciones_m.getText());

                                info.put("id_grupo", txtIDGrupoAfiliacion_m.getText());
                                info.put("id_base", txtIDBase_m.getText());

                                
                                
                            }
                            else{
                                JOptionPane.showMessageDialog(this, "Pais no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Estado no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Ciudad no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    
                    info.put("isMoving", false);

                    info.put("name_grupo", txtNameGrupoAfiliacion_m.getText());
                    info.put("desc_grupo", txtDescGrupoAfiliacion_m.getText());
                    info.put("name_base", txtBaseOperaciones_m.getText());
                    info.put("desc_base", txtDescBaseOperaciones_m.getText());

                    info.put("id_grupo", txtIDGrupoAfiliacion_m.getText());
                    info.put("id_base", txtIDBase_m.getText());
                }
        
                switch (GrupoAfiliacionC.updateGBAll(info)){
                    case 0:
                        fillTable();
                        txtNameGrupoAfiliacion_m.setText("");
                        txtDescGrupoAfiliacion_m.setText("");
                        txtBaseOperaciones_m.setText("");
                        txtDescBaseOperaciones_m.setText("");
                        txtIPA_m.setText("");
                        txtIDGrupoAfiliacion_m.setText("");
                        txtIDBase_m.setText("");
                        txtCiudad_m.setText("");
                        txtEstado_m.setText("");
                        txtPais_m.setText("");
                        isMoving.setSelected(false);
                        break;
                    case -1:
                        JOptionPane.showMessageDialog(this, "Error al insertar la direccion", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    case -2:
                        JOptionPane.showMessageDialog(this, "Error al actualizar el grupo de afiliacion", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    case -3:
                        JOptionPane.showMessageDialog(this, "Error al actualizar la base de operaciones", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Error al realizar update", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Nombre de la base no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Nombre del grupo no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUpdateGrupoAfiliacionActionPerformed
  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrupoAfiliacionList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGrupoAfiliacion;
    private javax.swing.JButton btnAtrasPL;
    private javax.swing.JButton btnDelGrupoAfiliacion;
    private javax.swing.JButton btnModGrupoAfiliacion;
    private javax.swing.JButton btnUpdateGrupoAfiliacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox isMoving;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panelModProfesion;
    private javax.swing.JTable tableGrupoAfiliacion;
    private javax.swing.JTextField txtBaseOperaciones;
    private javax.swing.JTextField txtBaseOperaciones_m;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCiudad_m;
    private javax.swing.JTextArea txtDescBaseOperaciones;
    private javax.swing.JTextArea txtDescBaseOperaciones_m;
    private javax.swing.JTextArea txtDescGrupoAfiliacion;
    private javax.swing.JTextArea txtDescGrupoAfiliacion_m;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstado_m;
    private javax.swing.JTextField txtIDBase_m;
    private javax.swing.JTextField txtIDGrupoAfiliacion;
    private javax.swing.JTextField txtIDGrupoAfiliacion_m;
    private javax.swing.JTextField txtIPA_m;
    private javax.swing.JTextField txtNameGrupoAfiliacion;
    private javax.swing.JTextField txtNameGrupoAfiliacion_m;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPais_m;
    // End of variables declaration//GEN-END:variables
}
